### PR TITLE
Fix going through MAM pagination in chats

### LINKED ISSUE #687: On new registration, history from MAM is truncated
I've just did a fresh installation of newest Movim and started some chats. I noticed that, although the history did fill up, the newest message available was from May. Subsequent reconnections eventually showed some newer messages, but only single ones from later dates, clearly cut out of context.

I've that already when installing v0.13 earlier. When the pod was running, history was gathered properly - seems it's just the process of bootstraping it from MAM that's buggy.

Server: ejabberd 18.06

### PR DESCRIPTION
**Pull request by dos1**
Fixes #687

### CODE REVIEW

File: lib/moxl/src/Moxl/Xec/Action/MAM/Get.php [hunk 1]
```diff
@@ -40,6 +40,18 @@ public function setBefore($before = true)
         return $this;
     }
 
+    public function setStart($start)
```
Comment (edhelas) [inline lib/moxl/src/Moxl/Xec/Action/MAM/Get.php]: I don't really get the need of those two methods, this piece of code is already taking care of that https://github.com/movim/movim/blob/master/lib/moxl/src/Moxl/Xec/Action.php#L50 :p

Comment (dos1) [reply lib/moxl/src/Moxl/Xec/Action/MAM/Get.php]: Ooooh. That explains a lot xD
